/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.CardLayout;// libreria que permite agregar layout
import java.net.URL; // libreria para importar desde direcciones
import javax.swing.ImageIcon; // libreria para agregar imagenes iconos
import javax.swing.SwingUtilities; // libreria para uso de swing

/**
 *
 * @author victor
 */
public final class menu_principal extends javax.swing.JFrame { //clase llamada menu_principal declarada de manera publica que hereda del frame jframe 

    panel_nuevo panel_nuevo = new panel_nuevo(); // instanciacion de panel_nuevo
    panel_buscar panel_buscar = new panel_buscar ();
    panel_eliminar  panel_eliminar = new  panel_eliminar ();
    panel_modificar panel_modificar = new panel_modificar ();

    CardLayout vista; // funcion para importar llamado vista 

    public menu_principal() { //constructor de la clase menu_principal 
        initComponents(); // constructor que inicializa los componentes 
        setExtendedState(MAXIMIZED_BOTH); //metodo setextended que funciona para ampliar nuestra interfaz grafica a pantalla completa 
        icon_abc();//mandamos llamar el metodo haciendo la clase final 
        vista = (CardLayout) vista_principal.getLayout(); //casteo de vista cardlayout
    }
// creamos un metodo para mostrar icono de programa

    public void icon_abc() { //creamos funcion tipo void ya que no devolvera y solo mostrara la imagen nada llamado  icon_abc
        URL url = getClass().getResource("/imagenes/icon abc.png"); // mandamos llamar la url la direccion donde se encuentra la imagen por medio del metodo getResource
        ImageIcon icono_formulario = new ImageIcon(url); // instanciamos el parametro url dentro de el nuevo objeto image icon 
        setIconImage(icono_formulario.getImage()); // establecemos la imagen con el metodo set icon image y lo invocamos a la ruta get image ()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        abc_buscar = new javax.swing.JToggleButton();
        abc_eliminar = new javax.swing.JToggleButton();
        abc_nuevo = new javax.swing.JToggleButton();
        abc_modificar = new javax.swing.JToggleButton();
        abc_salir = new javax.swing.JButton();
        vista_principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Multifuncional ABC -  CBTis 270");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("menu del sistema");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        abc_buscar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        abc_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        abc_buscar.setText("Buscar articulo ");
        abc_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        abc_buscar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        abc_buscar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        abc_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abc_buscarActionPerformed(evt);
            }
        });

        abc_eliminar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        abc_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        abc_eliminar.setText("Eliminar articulo ");
        abc_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        abc_eliminar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        abc_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        abc_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abc_eliminarActionPerformed(evt);
            }
        });

        abc_nuevo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        abc_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        abc_nuevo.setText("Registro de nuevo articulo");
        abc_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        abc_nuevo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        abc_nuevo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        abc_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abc_nuevoActionPerformed(evt);
            }
        });

        abc_modificar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        abc_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        abc_modificar.setText("Modificar datos de articulo");
        abc_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        abc_modificar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        abc_modificar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        abc_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abc_modificarActionPerformed(evt);
            }
        });

        abc_salir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        abc_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        abc_salir.setText("Salir");
        abc_salir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        abc_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abc_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abc_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abc_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abc_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abc_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abc_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(abc_nuevo)
                .addGap(54, 54, 54)
                .addComponent(abc_modificar)
                .addGap(53, 53, 53)
                .addComponent(abc_eliminar)
                .addGap(54, 54, 54)
                .addComponent(abc_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(abc_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        vista_principal.setBackground(new java.awt.Color(51, 153, 255));
        vista_principal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        vista_principal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abc_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abc_modificarActionPerformed
        vista_principal.add(panel_modificar, "modificar articulo"); // se adhiere el panel modificar articulo para mostrar en vista principal por medio de add a su vez ponemos referencia modificar 
        vista.show(vista_principal, "modificar articulo"); // se referencia vista que el nombre del layout
        SwingUtilities.updateComponentTreeUI(this); // se realiza una instanciacion haciendo uso de swing utilities 
         this.repaint();
                
    }//GEN-LAST:event_abc_modificarActionPerformed

    private void abc_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abc_nuevoActionPerformed

        vista_principal.add(panel_nuevo, "nuevo articulo"); // se adhiere el panel nuevo articulo para mostrar en vista principal por medio de add a su vez ponemos referencia nuevo 
        vista.show(vista_principal, "nuevo articulo"); // se referencia vista que el nombre del layout
        SwingUtilities.updateComponentTreeUI(this); // se realiza una instanciacion haciendo uso de swing utilities 
        this.repaint();

    }//GEN-LAST:event_abc_nuevoActionPerformed

    private void abc_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abc_eliminarActionPerformed
        vista_principal.add(panel_eliminar, "eliminar articulo"); // se adhiere el panel eliminar articulo para mostrar en vista principal por medio de add a su vez ponemos referencia eliminar
        vista.show(vista_principal, "eliminar articulo"); // se referencia vista que el nombre del layout
        SwingUtilities.updateComponentTreeUI(this); // se realiza una instanciacion haciendo uso de swing utilities 
        this.repaint();
    }//GEN-LAST:event_abc_eliminarActionPerformed

    private void abc_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abc_buscarActionPerformed
        vista_principal.add(panel_buscar, "buscar articulo"); // se adhiere el panel buscar articulo para mostrar en vista principal por medio de add a su vez ponemos referencia buscar  
        vista.show(vista_principal, "buscar articulo"); // se referencia vista que el nombre del layout
        SwingUtilities.updateComponentTreeUI(this); // se realiza una instanciacion haciendo uso de swing utilities 
        this.repaint();
    }//GEN-LAST:event_abc_buscarActionPerformed

    private void abc_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abc_salirActionPerformed
        System.exit(0); //metodo para terminar el proceso de la aplicacion
// TODO add your handling code here:
    }//GEN-LAST:event_abc_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new menu_principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton abc_buscar;
    private javax.swing.JToggleButton abc_eliminar;
    private javax.swing.JToggleButton abc_modificar;
    private javax.swing.JToggleButton abc_nuevo;
    private javax.swing.JButton abc_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel vista_principal;
    // End of variables declaration//GEN-END:variables
}
