
package calculadora;
// se declara un conjutno de clases e interfaces
// relacionadas entre si
import java.lang.Integer;
/**
 *
 * @author alex
 */
public class interfaz extends javax.swing.JFrame {
// se extendera la clase publica la interfaz con la clase utilizada
    // en swing(biblioteca grafica) para poder generar ventanas sobre las cuales
    // añadir distintos objetos con los que podra interactuar o no el ususaio
    
    /**
     * Creates new form interfaz
     */
    public interfaz() { 
        // se dara publico la clase que se creo llamada interfaz para que 
        // la clase calculadora puede detectarlo
        initComponents(); // lo que hace es que carga los objetos que
        // estan en el JFrame 
    }

    String numero1=""; // declaracion de la variable numero1 
    String numero2=""; // decdlaracion de la variable numero2
    int contador=0; // declaracion de la variable contador indicando que es entero
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // la funcion de esta linea es que indica que las avdertencias del compilador 
    // con nombre deben suprimisre en el elemento anotado
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        res = new javax.swing.JButton();
        sum = new javax.swing.JButton();
        resultado = new javax.swing.JButton();
        div = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        etiqueta3 = new javax.swing.JLabel();
        etiqueta1 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        potencia = new javax.swing.JButton();
        PI = new javax.swing.JButton();
        Bina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        num1.setText("1");
        num1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        getContentPane().add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 39, 39));

        num2.setText("2");
        num2.setMargin(new java.awt.Insets(2, 2, 2, 3));
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        getContentPane().add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 39, 39));

        num3.setText("3");
        num3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        getContentPane().add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 39, 39));

        num6.setText("6");
        num6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        getContentPane().add(num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 39, 39));

        num4.setText("4");
        num4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        getContentPane().add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 39, 39));

        num5.setText("5");
        num5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        getContentPane().add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 39, 39));

        num9.setText("9");
        num9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        getContentPane().add(num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 39, 39));

        num7.setText("7");
        num7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        getContentPane().add(num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 39, 39));

        num8.setText("8");
        num8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        getContentPane().add(num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 39, 39));

        res.setText("-");
        res.setMargin(new java.awt.Insets(2, 2, 2, 2));
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });
        getContentPane().add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 39, 39));

        sum.setText("+");
        sum.setMargin(new java.awt.Insets(2, 2, 2, 2));
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });
        getContentPane().add(sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 39, 39));

        resultado.setText("=");
        resultado.setMargin(new java.awt.Insets(2, 2, 2, 2));
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 39, 39));

        div.setText("/");
        div.setMargin(new java.awt.Insets(2, 2, 2, 2));
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        getContentPane().add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 39, 39));

        mul.setText("*");
        mul.setMargin(new java.awt.Insets(2, 2, 2, 2));
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });
        getContentPane().add(mul, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 39, 39));

        borrar.setText("C");
        borrar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 39, 39));

        punto.setText(".");
        punto.setMargin(new java.awt.Insets(2, 2, 2, 2));
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });
        getContentPane().add(punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 39, 39));

        num0.setText("0");
        num0.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        getContentPane().add(num0, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 39, 39));

        etiqueta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 60, 30));

        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 60, 30));

        etiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 60, 30));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 280, 40));

        jLabel2.setText("Calculadora");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        potencia.setText("^");
        potencia.setMargin(new java.awt.Insets(2, 2, 2, 2));
        potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaActionPerformed(evt);
            }
        });
        getContentPane().add(potencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 40, 40));

        PI.setText("PI");
        PI.setMargin(new java.awt.Insets(2, 2, 2, 2));
        PI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIActionPerformed(evt);
            }
        });
        getContentPane().add(PI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 40, 30));

        Bina.setText("Bina");
        Bina.setMargin(new java.awt.Insets(2, 2, 2, 2));
        Bina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinaActionPerformed(evt);
            }
        });
        getContentPane().add(Bina, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
       // esta parte declara el objeto creado para darle atributos y funcionamientos
        numero1 += "1"; // se declara que la variable numero1 que cada vez que se oprima ese boton se 
        // agrege ese caracter
        etiqueta3.setText(numero1); // lo que hace es que lo que tiene agregado la variable numero1
        // se agregara a la variable etiqueta 3 
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        numero1 += "2"; // se declara que la variable numero1 que cada vez que se oprima ese boton se 
        // agrege ese caracter
        etiqueta3.setText(numero1); 
        // lo que hace es que lo que tiene agregado la variable numero1
        // se agregara a la variable etiqueta 3 
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        numero1 += "3"; // se declara que la variable numero1 que cada vez que se oprima ese boton se 
        // agrege ese caracter
        etiqueta3.setText(numero1);
        // lo que hace es que lo que tiene agregado la variable numero1
        // se agregara a la variable etiqueta 3 
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        numero1 += "4"; // se declara que la variable numero1 que cada vez que se oprima ese boton se 
        // agrege ese caracter
        etiqueta3.setText(numero1);
        // lo que hace es que lo que tiene agregado la variable numero1
        // se agregara a la variable etiqueta 3 
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        numero1 += "5"; // se declara que la variable numero1 que cada vez que se oprima ese boton se 
        // agrege ese caracter
        etiqueta3.setText(numero1); // lo que hace es que lo que tiene agregado la variable numero1
        // se agregara a la variable etiqueta 3 
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        numero1 += "6"; // se declara que la variable numero1 que cada vez que se oprima ese boton se 
        // agrege ese caracter
        etiqueta3.setText(numero1); // lo que hace es que lo que tiene agregado la variable numero1
        // se agregara a la variable etiqueta 3 
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        numero1 += "7"; // se declara que la variable numero1 que cada vez que se oprima ese boton se 
        // agrege ese caracter
        etiqueta3.setText(numero1);// lo que hace es que lo que tiene agregado la variable numero1
        // se agregara a la variable etiqueta 3 
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        numero1 += "8"; // se declara que la variable numero1 que cada vez que se oprima ese boton se 
        // agrege ese caracter
        etiqueta3.setText(numero1); // lo que hace es que lo que tiene agregado la variable numero1
        // se agregara a la variable etiqueta 3 
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        numero1 += "9"; // se declara que la variable numero1 que cada vez que se oprima ese boton se 
        // agrege ese caracter
        etiqueta3.setText(numero1); // lo que hace es que lo que tiene agregado la variable numero1
        // se agregara a la variable etiqueta 3 
    }//GEN-LAST:event_num9ActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        numero1 += "."; // se declara que la variable numero1 que cada vez que se oprima ese boton se 
        // agrege ese caracter
        // puede ser acumulable para seguir agregando puntos
        etiqueta3.setText(numero1); // lo que hace es que lo que tiene agregado la variable numero1
        // se agregara a la variable etiqueta 3 
    }//GEN-LAST:event_puntoActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        numero1 += "0"; // se declara que la variable numero1 que cada vez que se oprima ese boton se 
        // agrege ese caracter
        etiqueta3.setText(numero1); // lo que hace es que lo que tiene agregado la variable numero1
        // se agregara a la variable etiqueta 3 
    }//GEN-LAST:event_num0ActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        numero1=""; // declaracion de que las variables estaran vacias
        numero2=""; // declaracion de que las variables estaran vacias
        etiqueta1.setText(""); // remplazara lo que tiene la etiqueta1 a ""
        etiqueta2.setText("");  // remplazara lo que tiene la etiqueta2 a ""
        etiqueta3.setText("");  // remplazara lo que tiene la etiqueta3 a ""
        contador =0; // declaracion de que las variables estaran vacias
        
    }//GEN-LAST:event_borrarActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
        if(!etiqueta3.getText().equals("")|| contador!= 0){
            // la parte del getText sirve para obtener un texto(string), devuelva el valor 
            // equals compara si 2 objetos apuntan al mismo objeto
        operaciones(); // va a llamar a la clase operaciones
        etiqueta2.setText("x"); 
        }
    }//GEN-LAST:event_mulActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        if(!etiqueta3.getText().equals("")|| contador!= 0){
            // si es diferente de la etiqueta3 no ha texto entonces pasa a operaciones 
            // o si el contador es diferente de 0
            // la parte del getText sirve para obtenr un texto o valor(String) devuelve el valor
            // equals compara si 2 objetos apuntan al mismo objeto 
        operaciones(); // va a llamar a la clase operaciones para seguir con otro procedimiento
        etiqueta2.setText("+"); // lo que hara en esta parte es que 
        // al dar el boton de suma, este imprimira "+"
        }
    }//GEN-LAST:event_sumActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        if(!etiqueta3.getText().equals("")|| contador!= 0){
            // la parte de getText es para obtener un texto(en este caso string)
            // equals tiene como funcion comparar si 2 objetos aountan al mismo objeto    
        operaciones(); // va a llamar a la clase operaciones para continuar con otras operaciones
        etiqueta2.setText(""); // al dar click en el boton de Resultado, lo que 
        // hara es que dejara vacio la etiqueta 2, osea imprimiria "" pero no hay una letra que aparezca
        
        }
    }//GEN-LAST:event_resultadoActionPerformed

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
        if(!etiqueta3.getText().equals("")|| contador!= 0){
            // la parte de getText es para obtener un texto(en este caso string)
            // equals tiene como funcion comparar si 2 objetos aountan al mismo objeto
        operaciones(); // va a mandar a llamar la funcion de operaciones
        etiqueta2.setText("-");// lo que hace es que imprime un - en la etiqueta 2 puesta 
        // en el diseño
        }
    }//GEN-LAST:event_resActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        if(!etiqueta3.getText().equals("")|| contador!= 0){
            // la parte de getText es para obtener un texto(en este caso string)
            // equals tiene como funcion comparar si 2 objetos apuntan al mismo objeto
        operaciones(); // llamara a la funcion de operaciones si se cumple con
        // la condicional
        etiqueta2.setText("/"); // se imprimira un / al dar un click en el boton 
        // de Division
        }
    }//GEN-LAST:event_divActionPerformed

    private void potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaActionPerformed
        if(!etiqueta3.getText().equals("")|| contador!=0){
            // la parte de getText es para obtener un texto(en este caso string)
            // equals tiene como funcion comparar si 2 objetos aountan al mismo objeto
         operaciones(); // se llamara la funcion de operaciones para ejecutar otra operaciones
         etiqueta2.setText("^"); // se imprimira un ^ al dar clik en el boton de Potencia
         
        }
        
    }//GEN-LAST:event_potenciaActionPerformed

    private void PIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIActionPerformed
        numero1 = "3.1416"; // se declara que la variable numero1 que cada vez que se oprima ese boton se 
        // agrege ese caracter
      
        etiqueta3.setText(numero1); // se imprime en la etiqueta3  lo que esta guardado en numero1
        // en este caso imprimiria 3.1416
    
    }//GEN-LAST:event_PIActionPerformed

    private void BinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinaActionPerformed
        if(!etiqueta3.getText().equals("")|| contador!=0){
            // la parte de getText es para obtener un texto(en este caso string)
            // equals tiene como funcion comparar si 2 objetos aountan al mismo objeto
         operaciones(); // se llamara la funcion de operaciones para ejecutar otra operaciones
         etiqueta2.setText("Binary"); // se imprimira un Binary al dar clik en el boton de binario
        }
    }//GEN-LAST:event_BinaActionPerformed
  
    void operaciones(){
        // se declara la clase operaciones
        double n1,n2; // declaracion de variables n1 y n2
        String n3;
        if(!etiqueta3.getText().equals("")){
            // si etiqueta3 no tiene texto entonces se cumple la condicion
            // la parte de getText es para obtener un texto(en este caso string)
            // equals tiene como func numero2
           
         if(contador==0){ 
             // condicionales diciendo que si contador
          numero2=numero1; // el valor de numero1 se pasa al
      
      }
     if(numero2.equals("")){
         // compara si 2 objetos apuntan al mismo objeto 
      numero2="0";
      
      }
     n1 = Double.valueOf(numero2); // n1 tendra los valores que se hayan puesto en la variable numero2
     n2 = Double.valueOf(numero1); // n2 tendra los valores que se hayan puesto en la variable numero1
     n3= String.valueOf(numero1); 
     if(etiqueta2.getText().equals("-")){
         // si  etiqueta2 contiene un "-" entonces se cumple la condicion 
     numero2=String.valueOf(n1-n2); // si es que se cumple la condicional entonces las variables n1 y n2 se restaran
     // y se mandara el resultado a l variable de numero2 
      }
     if(etiqueta2.getText().equals("+")){
         // si  etiqueta2 contiene un "+" entonces se cumple la condicion 
     numero2=String.valueOf(n1+n2); // si es que se cumple la condicional entonces las variables n1 y n2 se sumaran
     // y se mandara el resultado a l variable de numero2 
      }
     if(etiqueta2.getText().equals("x")){
         // si  etiqueta2 contiene un "x" entonces se cumple la condicion 
     numero2=String.valueOf(n1*n2); // si es que se cumple la condicional entonces las variables n1 y n2 se multiplicaran
     // y se mandara el resultado a l variable de numero2 
     }
     if(etiqueta2.getText().equals("/")){
         // si  etiqueta2 contiene un "/" entonces se cumple la condicion 
     numero2=String.valueOf(n1/n2); // si es que se cumple la condicional entonces las variables n1 y n2 se dividiran
     // y se mandara el resultado a l variable de numero2 
      }
     if(etiqueta2.getText().equals("^")){
         // si  etiqueta2 contiene un "^" entonces se cumple la condicion 
     numero2=String.valueOf(Math.pow(n1,n2)); // si es que se cumple la condicional entonces n1 se incrementara a la potencia que contenga n2
     // y se mandara el resultado a l variable de numero2 
     }
     if(etiqueta2.getText().equals("Bina")){
         
         String Num=null;
         Num=etiqueta1.getText();
         Conversion CN=new Conversion();
         etiqueta3.getText(CN.intoHex(new Integer(Num)));
     }
     etiqueta3.setText(""); // en la etiqueta3 se imprime un ""
     numero1=""; //numero1 quedara declarado como ""
     contador++; // la variable contador se sumara de uno en uno 
     etiqueta1.setText(numero2); // los datos que tenga la variable de numero2 se imprimira en la etiqueta1
     }
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bina;
    private javax.swing.JButton PI;
    private javax.swing.JButton borrar;
    private javax.swing.JButton div;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiqueta3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mul;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton potencia;
    private javax.swing.JButton punto;
    private javax.swing.JButton res;
    private javax.swing.JButton resultado;
    private javax.swing.JButton sum;
    // End of variables declaration//GEN-END:variables
}
